fix: `license_url` between quotes
Possible fix for this error:
```
  File "<string>", line 1
    from tools.operations import *; update_gtfs_realtime_source(mdb_source_id="", entity_type="GTFS Realtime - Trip Updates", provider="Arlington Transit", direct_download_url="https://realtime.arlingtontransit.com/gtfsrt/trips", authentication_type="", authentication_info_url="0 or (empty) - No authentication required.", api_key_parameter_name="", license_url= Redmon Group Inc", name="", static_reference="TO_BE_PROVIDED", note="", status="", features="Active")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ^
SyntaxError: unterminated string literal (detected at line 1)
Error: Process completed with exit code 1.
```