Fix script that processes feeds (#310)
* fix: switch to column E for schedule, H for RT

Also, minor fixes, plus ternary operator if one URL is empty, use the other.

* Fix for data type for real time

Needed to provide an array to the entity_type value (vp, tu, sa, default ug).

* fix: missing realtime type when column G is empty

* fix: added logic when provider cell empty

Store last known provider (with default to `TO_BE_PROVIDED`), and use it as a suggestion if the cell is empty.

* fix: Used constant instead of plain string

* fix: `license_url` between quotes

Possible fix for this error:
```
  File "<string>", line 1
    from tools.operations import *; update_gtfs_realtime_source(mdb_source_id="", entity_type="GTFS Realtime - Trip Updates", provider="Arlington Transit", direct_download_url="https://realtime.arlingtontransit.com/gtfsrt/trips", authentication_type="", authentication_info_url="0 or (empty) - No authentication required.", api_key_parameter_name="", license_url= Redmon Group Inc", name="", static_reference="TO_BE_PROVIDED", note="", status="", features="Active")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ^
SyntaxError: unterminated string literal (detected at line 1)
Error: Process completed with exit code 1.
```

* fix: if license_url is invalid, provide context

* Fix: add pip upgrade to remove warning in log

* fix: changes to correct errors in Python script